
# docker-copose.yml

 
version: "3" 

services:
  wpt:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./WPT:/WPT

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"


    