
# docker-copose.yml
 
version: "3" 

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/WPT/backend

    command: >
      sh -c "python backend/manage.py runserver 0.0.0.0:8000"
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend:/WPT/frontend
    depends_on: 
      - backend


    