# Generated by Django 3.1.7 on 2021-04-26 12:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_muscle"),
        ("users", "0001_initial"),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="exercises",
            field=models.ManyToManyField(blank=True, to="exercises.ExerciseSet"),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="muscles",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Calves", "Calves"),
                    ("Hamstrings", "Hamstrings"),
                    ("quads", "Quadriceps(quads)"),
                    ("glutes", "Glutes"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("forearms", "Forearms"),
                    ("traps", "Trapezius(traps)"),
                ],
                default=None,
                max_length=100,
            ),
        ),
    ]
