# Generated by Django 3.1.6 on 2021-02-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Program",
        ),
    ]
