# Generated by Django 3.1.7 on 2021-03-31 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='muscles',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='muscles',
            field=models.CharField(choices=[('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quads', 'Quadriceps(quads)'), ('glutes', 'Glutes'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('traps', 'Trapezius(traps)')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
