# Generated by Django 3.1.7 on 2021-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="muscles",
            field=models.CharField(
                choices=[
                    ("Calves", "Calves"),
                    ("Hamstrings", "Hamstrings"),
                    ("quads", "Quadriceps(quads)"),
                    ("glutes", "Glutes"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("forearms", "Forearms"),
                    ("traps", "Trapezius(traps)"),
                ],
                default=None,
                max_length=100,
            ),
        ),
    ]
