# Generated by Django 3.1.7 on 2021-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_muscle"),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="exercises",
            field=models.ManyToManyField(
                blank=True, null=True, to="exercises.ExerciseSet"
            ),
        ),
    ]
