# Generated by Django 3.1.7 on 2021-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210331_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='muscles',
            field=models.CharField(choices=[('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quads', 'Quadriceps(quads)'), ('glutes', 'Glutes'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('traps', 'Trapezius(traps)')], default=None, max_length=100),
        ),
    ]
