# Generated by Django 3.1.6 on 2021-02-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_workoutlog_muscles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutlog",
            old_name="summary",
            new_name="short_note",
        ),
        migrations.RemoveField(
            model_name="workoutlog",
            name="name",
        ),
    ]
