# Generated by Django 3.1.6 on 2021-02-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_auto_20210226_2009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="short_note",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
