# Generated by Django 3.1.6 on 2021-02-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_auto_20210227_1043"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutlog",
            name="name",
        ),
    ]
